
springdoc:
  api-docs:
    path: /api-docs # Default path for the JSON OpenAPI definition
  swagger-ui:
    path: /swagger-ui.html # Path to access the Swagger UI

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/collab_db?createDatabaseIfNotExist=true
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          github:

            scope: repo

server:
  port: 4444
