
springdoc:
  api-docs:
    path: /api-docs # Default path for the JSON OpenAPI definition
  swagger-ui:
    path: /swagger-ui.html # Path to access the Swagger UI

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/collab_db?createDatabaseIfNotExist=true
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          github:
            client-secret: 1959f7ea845f8f4554e4fb6af07ed7c7b862f777
            client-id: Iv23lignrKAI3mPDNSNI
            scope: repo,read:user,user:email
        provider:
          github:
            user-info-uri: https://api.github.com/user



server:
  port: 4444
