spring:
  githubBaseUrl: https://github.com
  datasource:
    url: jdbc:postgresql://localhost:5432/collab_db?createDatabaseIfNotExist=true
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  oauth2:
    client: Ov23liIKWhTiZABJRTQd
    authorizeUrl: login/oauth/authorize
    redirectUri: http://localhost:8080/api/authorize
    scopes: public_repo

server:
  port: 4444
